### ISSUE TITLE
OneDrive Personal uses a different endpoint than Business

### ISSUE THREAD

**Issue by MartyMacGyver** [O365/python-o365#234]
[Per Microsoft's documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences?view=odsp-graph-online#onedrive-personal-accounts)

_"To access OneDrive API for OneDrive personal, your app must use the https://api.onedrive.com/v1.0 endpoint for all requests."_

I'm still working through the O365 docs here, but already I see not everything I'd expect to be working works, and I think this is related to that.

**Comment by janscas** [comment]
That’s if you are using the onedrive rest api.
This library does not so you can use both personal and work accounts.

Both work (I test it myself)

**Comment by MartyMacGyver** [comment]
And yet endpoints I'd expect to work (and which certainly do exist) do not work using the Graph API. For example:

`HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drive/special/OneDriveWellKnowFolderNames.ATTACHMENTS | Error Message: Unknown special folder name: OneDriveWellKnowFolderNames.ATTACHMENTS`

`Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drive/special/OneDriveWellKnowFolderNames.DOCUMENTS | Error Message: Unknown special folder name: OneDriveWellKnowFolderNames.DOCUMENTS`

It is interesting that the documentation suggests at first that Graph API is preferred, but goes on to later make a distinction between business and personal OneDrive APIs.

I'm also not sure what this error got `storage.get_drives()` is all about:

`Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drives?%24top=999 | Error Message: The query specified in the URI is not valid. Query option 'Top' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.`

Is it a permissions thing? Is there some delegated permission required beyond what's in the examples here?

**Comment by janscas** [comment]
Let's go one by one:

> `my_drive.get_special_folder('attachments')` gives `HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drive/special/OneDriveWellKnowFolderNames.ATTACHMENTS | Error Message: Unknown special folder name: OneDriveWellKnowFolderNames.ATTACHMENTS`

This was an error on the library. It is fixed now. I was passing the enum str and not the actual value.


> Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drives?%24top=999 | Error Message: The query specified in the URI is not valid. Query option 'Top' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.

This was also a bug. the '/drives' enpoint did not accept a top parameter.

**Comment by janscas** [comment]
A new pypi version is now released (v1.1.7)

**Comment by MartinFalatic** [comment]
Ah, I didn't realize it was a bug! Thanks for resolving it.

**Comment by MartyMacGyver** [comment]
Ah, I didn't realize it was a bug! Thanks for resolving it.

**Comment by bobbrandTB** [comment]
I have version 2.0.7 from pypi and I still have this same error:

 Client Error: Bad Request for url: https://graph.microsoft.com/beta/me/drives?%24top=999 | Error Message: The query specified in the URI is not valid. Query option 'Top' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings that was described as fixed in v1.1.7

**Comment by janscas** [comment]
Someone re-introduce this bug. I'll commit a new patch. Thanks

**Comment by cgarmstr** [comment]
I have the same issue when trying to run onedrive_example.py, i.e. HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drives?%24top=999 | Error Message: The query specified in the URI is not valid. Query option 'Top' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.
